quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=2

%test.quarkus.datasource.devservices.reuse=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-migration-naming=true

user-service.security.argon2.memory=65536
user-service.security.argon2.iterations=3
user-service.security.argon2.parallelism=4